"""
VALE FEELINGS Brain
Empathy Perspective Model

File:
    FEEL/empathy/perspective.py

Purpose:
    Model another person's possible perspective of a situation.

Core principle:

    OBSERVED INFORMATION
            ↓
    CONTEXT
            ↓
    POSSIBLE PERSPECTIVES
            ↓
    POSSIBLE INTERPRETATIONS
            ↓
    UNCERTAINTY
            ↓
    COMMUNICATION IMPLICATIONS

This subsystem does not claim to know what another person actually thinks
or feels. It generates bounded perspective hypotheses from available
evidence and context.

Important epistemic boundary:

    FACT != INFERENCE != HYPOTHESIS

A perspective generated by this module is an inference/hypothesis unless
the person explicitly stated it.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence

from FEEL.core.models import (
    ConfidenceLevel,
    EvidenceReference,
    EpistemicClaim,
    EpistemicType,
)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _clamp(
    value: float,
    minimum: float = 0.0,
    maximum: float = 1.0,
) -> float:
    return max(minimum, min(maximum, float(value)))


def _safe_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _unique(values: Iterable[str]) -> List[str]:
    result: List[str] = []
    seen = set()

    for value in values:
        value = _safe_text(value)

        if not value:
            continue

        key = value.casefold()

        if key not in seen:
            seen.add(key)
            result.append(value)

    return result


# ---------------------------------------------------------------------------
# Perspective models
# ---------------------------------------------------------------------------

@dataclass
class PerspectiveSignal:
    """
    A single possible perspective or interpretation.

    `is_explicit` means the perspective is directly supported by an
    explicit statement from the person.

    Otherwise it should be treated as an inference/hypothesis.
    """

    perspective: str

    interpretation: str

    confidence: float = 0.0

    relevance: float = 0.0

    is_explicit: bool = False

    evidence: List[EvidenceReference] = field(default_factory=list)

    alternative_explanations: List[str] = field(
        default_factory=list
    )

    uncertainties: List[str] = field(
        default_factory=list
    )

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class EmpathyPerspectiveModel:
    """
    Complete perspective model produced for a situation.
    """

    situation: str = ""

    observed_information: List[str] = field(
        default_factory=list
    )

    explicit_perspectives: List[PerspectiveSignal] = field(
        default_factory=list
    )

    inferred_perspectives: List[PerspectiveSignal] = field(
        default_factory=list
    )

    possible_concerns: List[str] = field(
        default_factory=list
    )

    possible_priorities: List[str] = field(
        default_factory=list
    )

    possible_interpretations: List[str] = field(
        default_factory=list
    )

    communication_implications: List[str] = field(
        default_factory=list
    )

    uncertainties: List[str] = field(
        default_factory=list
    )

    alternative_explanations: List[str] = field(
        default_factory=list
    )

    confidence: float = 0.0

    epistemic_claims: List[EpistemicClaim] = field(
        default_factory=list
    )

    evidence: List[EvidenceReference] = field(
        default_factory=list
    )

    reasoning_notes: List[str] = field(
        default_factory=list
    )

    created_at: datetime = field(
        default_factory=_utc_now
    )

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Perspective engine
# ---------------------------------------------------------------------------

class EmpathyPerspectiveEngine:
    """
    Generate bounded possible perspectives.

    The engine deliberately avoids statements such as:

        "The person feels X."

    and instead produces:

        "The person may interpret X as..."

        "One possible concern is..."

        "This could indicate..."

    unless the information is explicitly stated by the person.
    """

    ENGINE_NAME = "empathy_perspective"
    VERSION = "0.1.0"

    # Signals that commonly provide useful perspective information.
    CONCERN_PATTERNS = {
        "risk": (
            "risk",
            "danger",
            "unsafe",
            "problem",
            "threat",
            "lose",
            "loss",
        ),
        "uncertainty": (
            "don't know",
            "not sure",
            "uncertain",
            "confused",
            "unclear",
            "what if",
        ),
        "time": (
            "deadline",
            "urgent",
            "asap",
            "quickly",
            "late",
            "time",
        ),
        "accuracy": (
            "mistake",
            "wrong",
            "correct",
            "accurate",
            "accuracy",
            "verify",
        ),
        "control": (
            "control",
            "choose",
            "decision",
            "decide",
            "my choice",
        ),
        "understanding": (
            "explain",
            "understand",
            "meaning",
            "how",
            "why",
            "what does",
        ),
        "outcome": (
            "result",
            "outcome",
            "work",
            "success",
            "fail",
            "failure",
        ),
    }

    PRIORITY_PATTERNS = {
        "clarity": (
            "explain",
            "clear",
            "understand",
            "meaning",
        ),
        "speed": (
            "quick",
            "fast",
            "urgent",
            "asap",
            "now",
        ),
        "accuracy": (
            "correct",
            "accurate",
            "verify",
            "proof",
            "evidence",
        ),
        "safety": (
            "safe",
            "risk",
            "danger",
            "protect",
        ),
        "control": (
            "choose",
            "decision",
            "control",
            "option",
        ),
        "practical_action": (
            "how do",
            "steps",
            "fix",
            "solve",
            "do this",
        ),
    }

    def __init__(self) -> None:
        self.last_model: Optional[
            EmpathyPerspectiveModel
        ] = None

    # ------------------------------------------------------------------
    # Input handling
    # ------------------------------------------------------------------

    def _extract_text(self, context: Any) -> str:
        """
        Extract conversational text from common VALE context structures.
        """

        if context is None:
            return ""

        if isinstance(context, str):
            return context.strip()

        if isinstance(context, Mapping):
            for key in (
                "text",
                "message",
                "user_message",
                "content",
                "query",
                "situation",
            ):
                value = _safe_text(context.get(key))

                if value:
                    return value

            return ""

        for attribute in (
            "text",
            "message",
            "user_message",
            "content",
            "query",
            "situation",
        ):
            if hasattr(context, attribute):
                value = _safe_text(
                    getattr(context, attribute)
                )

                if value:
                    return value

        return ""

    def _extract_observations(
        self,
        context: Any,
        text: str,
    ) -> List[str]:
        """
        Extract only observable/explicit information.

        This method intentionally does not convert assumptions into facts.
        """

        observations: List[str] = []

        if text:
            observations.append(
                f"User provided: {text}"
            )

        if isinstance(context, Mapping):
            explicit_keys = (
                "observed_events",
                "known_context",
                "facts",
                "explicit_information",
                "constraints",
            )

            for key in explicit_keys:
                value = context.get(key)

                if isinstance(value, Sequence) and not isinstance(
                    value,
                    (str, bytes),
                ):
                    observations.extend(
                        _safe_text(item)
                        for item in value
                        if _safe_text(item)
                    )

                elif value:
                    observations.append(
                        _safe_text(value)
                    )

        return _unique(observations)

    # ------------------------------------------------------------------
    # Pattern detection
    # ------------------------------------------------------------------

    def _contains_pattern(
        self,
        text: str,
        pattern: str,
    ) -> bool:
        return pattern.casefold() in text.casefold()

    def _detect_categories(
        self,
        text: str,
        patterns: Mapping[str, Sequence[str]],
    ) -> List[str]:
        categories: List[str] = []

        for category, category_patterns in patterns.items():
            if any(
                self._contains_pattern(text, pattern)
                for pattern in category_patterns
            ):
                categories.append(category)

        return categories

    # ------------------------------------------------------------------
    # Explicit perspective extraction
    # ------------------------------------------------------------------

    def _extract_explicit_perspective(
        self,
        context: Any,
    ) -> List[PerspectiveSignal]:
        """
        Extract perspective statements that were explicitly supplied.

        Supported fields:

            explicit_perspective
            explicit_perspectives
            stated_feelings
            stated_concerns
            stated_priorities
            user's_perspective
        """

        perspectives: List[PerspectiveSignal] = []

        if not isinstance(context, Mapping):
            return perspectives

        explicit_keys = (
            "explicit_perspective",
            "explicit_perspectives",
            "stated_feelings",
            "stated_concerns",
            "stated_priorities",
            "user_perspective",
            "users_perspective",
        )

        for key in explicit_keys:
            value = context.get(key)

            if value is None:
                continue

            values: List[Any]

            if isinstance(value, Sequence) and not isinstance(
                value,
                (str, bytes),
            ):
                values = list(value)
            else:
                values = [value]

            for item in values:
                text = _safe_text(item)

                if not text:
                    continue

                perspectives.append(
                    PerspectiveSignal(
                        perspective="explicit user perspective",
                        interpretation=text,
                        confidence=1.0,
                        relevance=1.0,
                        is_explicit=True,
                        uncertainties=[],
                        alternative_explanations=[],
                        metadata={
                            "source": key,
                            "epistemic_type": (
                                EpistemicType.FACT.value
                                if hasattr(
                                    EpistemicType,
                                    "value",
                                )
                                else "fact"
                            ),
                        },
                    )
                )

        return perspectives

    # ------------------------------------------------------------------
    # Inferred perspective generation
    # ------------------------------------------------------------------

    def _generate_inferred_perspectives(
        self,
        text: str,
    ) -> List[PerspectiveSignal]:
        """
        Generate possible interpretations from observable language.

        These are deliberately hypotheses rather than conclusions.
        """

        perspectives: List[PerspectiveSignal] = []

        concern_categories = self._detect_categories(
            text,
            self.CONCERN_PATTERNS,
        )

        priority_categories = self._detect_categories(
            text,
            self.PRIORITY_PATTERNS,
        )

        # --------------------------------------------------------------
        # Risk
        # --------------------------------------------------------------

        if "risk" in concern_categories:
            perspectives.append(
                PerspectiveSignal(
                    perspective="risk-sensitive perspective",
                    interpretation=(
                        "The person may be evaluating the situation "
                        "primarily through possible negative consequences."
                    ),
                    confidence=0.55,
                    relevance=0.75,
                    alternative_explanations=[
                        "Risk-related wording may simply describe "
                        "the task rather than the person's perspective."
                    ],
                    uncertainties=[
                        "No direct statement confirms that risk is "
                        "the person's dominant concern."
                    ],
                )
            )

        # --------------------------------------------------------------
        # Uncertainty
        # --------------------------------------------------------------

        if "uncertainty" in concern_categories:
            perspectives.append(
                PerspectiveSignal(
                    perspective="uncertainty-sensitive perspective",
                    interpretation=(
                        "The person may primarily need clearer "
                        "information or reduced ambiguity."
                    ),
                    confidence=0.62,
                    relevance=0.78,
                    alternative_explanations=[
                        "The wording may reflect ordinary information "
                        "seeking rather than significant uncertainty."
                    ],
                    uncertainties=[
                        "The available text does not establish the "
                        "degree of uncertainty."
                    ],
                )
            )

        # --------------------------------------------------------------
        # Time pressure
        # --------------------------------------------------------------

        if "time" in concern_categories:
            perspectives.append(
                PerspectiveSignal(
                    perspective="time-sensitive perspective",
                    interpretation=(
                        "The person may place significant value on "
                        "speed or immediate progress."
                    ),
                    confidence=0.64,
                    relevance=0.8,
                    alternative_explanations=[
                        "Urgency language may describe task constraints "
                        "rather than emotional pressure."
                    ],
                )
            )

        # --------------------------------------------------------------
        # Accuracy
        # --------------------------------------------------------------

        if "accuracy" in concern_categories:
            perspectives.append(
                PerspectiveSignal(
                    perspective="accuracy-sensitive perspective",
                    interpretation=(
                        "The person may prioritize correctness, "
                        "verification, or avoiding mistakes."
                    ),
                    confidence=0.66,
                    relevance=0.82,
                    alternative_explanations=[
                        "Accuracy language may be a normal requirement "
                        "of the task rather than a personal concern."
                    ],
                )
            )

        # --------------------------------------------------------------
        # Control
        # --------------------------------------------------------------

        if "control" in concern_categories:
            perspectives.append(
                PerspectiveSignal(
                    perspective="autonomy/control perspective",
                    interpretation=(
                        "The person may place importance on retaining "
                        "choice or understanding available options."
                    ),
                    confidence=0.53,
                    relevance=0.68,
                    alternative_explanations=[
                        "Decision language may be purely task-oriented."
                    ],
                )
            )

        # --------------------------------------------------------------
        # Understanding
        # --------------------------------------------------------------

        if "understanding" in concern_categories:
            perspectives.append(
                PerspectiveSignal(
                    perspective="understanding-oriented perspective",
                    interpretation=(
                        "The person may primarily need a clear "
                        "explanation rather than only an answer."
                    ),
                    confidence=0.69,
                    relevance=0.84,
                    alternative_explanations=[
                        "A question may simply request a concise fact."
                    ],
                )
            )

        # --------------------------------------------------------------
        # Outcome
        # --------------------------------------------------------------

        if "outcome" in concern_categories:
            perspectives.append(
                PerspectiveSignal(
                    perspective="outcome-oriented perspective",
                    interpretation=(
                        "The person may be focused on the practical "
                        "result or consequence of the situation."
                    ),
                    confidence=0.56,
                    relevance=0.72,
                    alternative_explanations=[
                        "Outcome-related language may simply reflect "
                        "the structure of the task."
                    ],
                )
            )

        return perspectives

    # ------------------------------------------------------------------
    # Communication implications
    # ------------------------------------------------------------------

    def _communication_implications(
        self,
        perspectives: Sequence[PerspectiveSignal
